# Updates the repo Wiki from the './docs' folder.

name: Documentation

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          submodules: recursive
      - name: Upload ./docs/ to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: 'docs'
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
